### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/tvseries#41]
Port the existing MIT LICENSE in the README.md to LICENSE.md file.

**Comment by nikhilmufc7** [comment]
It already exists, do you need any other license?

**Comment by nguptaa183** [comment]
I would like to contribute to this :)

**Comment by nguptaa183** [comment]
> It already exists, do you need any other license?

Even I didn't get this :o

**Comment by athityakumar** [comment]
Sorry, this has already been done and I forgot to close the issue - my bad! 🙈
